name: Build WebAssembly R Package

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build WebAssembly R package
        uses: r-wasm/actions/build-rwasm@v1
        with:
          packages: 'github::idot/shinyngs'
          strip: "demo, doc, examples, help, html, include, tests, vignette"
          image-path: 'wasm-lib'
          repo-path: '_repo'

      - name: Upload WASM library
        uses: actions/upload-artifact@v3
        with:
          name: shinyngs-wasm-lib
          path: wasm-lib

      - name: Upload WASM repository
        uses: actions/upload-artifact@v3
        with:
          name: shinyngs-wasm-repo
          path: _repo

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _repo
          keep_files: false